/*
 * Copyright (c) 2017, embedjournal.com
 *
 * SPDX-License-Identifier: Apache-2.0
 */

#include <kernel.h>
#include <device.h>
#include <init.h>
#include <drivers/pinmux.h>

#define GD32_PINMUX_FUNC_USART0_TX (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_USART0_RX (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_USART1_TX (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_USART1_RX (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_USART2_TX (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_USART2_RX (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_UART3_TX  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_UART3_RX  (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_UART4_TX  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_UART4_RX  (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_I2C0_SCL  (GPIO_MODE_AF_OD|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_I2C0_SDA  (GPIO_MODE_AF_OD|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_I2C1_SCL  (GPIO_MODE_AF_OD|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_I2C1_SDA  (GPIO_MODE_AF_OD|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI0_MASTER_NSS  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI0_MASTER_SCK  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI0_MASTER_MISO (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI0_MASTER_MOSI (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI1_MASTER_NSS  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI1_MASTER_SCK  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI1_MASTER_MISO (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI1_MASTER_MOSI (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI0_SLAVE_NSS   (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI0_SLAVE_SCK   (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI0_SLAVE_MISO  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI0_SLAVE_MOSI  (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI1_SLAVE_NSS   (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI1_SLAVE_SCK   (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_SPI1_SLAVE_MISO  (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_SPI1_SLAVE_MOSI  (GPIO_MODE_IN_FLOATING)
#define GD32_PINMUX_FUNC_CAN0_TX          (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_CAN0_RX          (GPIO_MODE_IPU)
#define GD32_PINMUX_FUNC_CAN1_TX          (GPIO_MODE_AF_PP|GPIO_OSPEED_50MHZ)
#define GD32_PINMUX_FUNC_CAN1_RX          (GPIO_MODE_IPU)


#define PINMUX_SET(func,port,pin) pinmux_pin_set(port, pin, GD32_PINMUX_FUNC_##func)

static int pinmux_gd32_init(struct device *port)
{
#define PA device_get_binding(DT_GPIO_GD32_GPIOA_LABEL)
#define PB device_get_binding(DT_GPIO_GD32_GPIOB_LABEL)
#define PC device_get_binding(DT_GPIO_GD32_GPIOC_LABEL)
#define PD device_get_binding(DT_GPIO_GD32_GPIOD_LABEL)
#define PE device_get_binding(DT_GPIO_GD32_GPIOE_LABEL)

	ARG_UNUSED(port);

#ifdef CONFIG_UART_0
	PINMUX_SET(USART0_TX, PA,9);
	PINMUX_SET(USART0_RX, PA,10);
#endif	/* CONFIG_UART_0 */
#ifdef CONFIG_UART_1
	PINMUX_SET(USART1_TX, PA,2);
	PINMUX_SET(USART1_RX, PA,3);
#endif	/* CONFIG_UART_1 */
#ifdef CONFIG_UART_2
	PINMUX_SET(USART2_TX, PB,10);
	PINMUX_SET(USART2_RX, PB,11);
#endif	/* CONFIG_UART_2 */
#ifdef CONFIG_UART_3
	PINMUX_SET(UART3_TX, PC,10);
	PINMUX_SET(UART3_RX, PC,11);
#endif	/* CONFIG_UART_3 */
#ifdef CONFIG_UART_4
	PINMUX_SET(UART4_TX, PC,12);
	PINMUX_SET(UART4_RX, PD,2);
#endif	/* CONFIG_UART_4 */
#ifdef CONFIG_I2C_0
	PINMUX_SET(I2C0_SCL, PB,6);
	PINMUX_SET(I2C0_SDA, PB,7);
#endif /* CONFIG_I2C_1 */
#ifdef CONFIG_I2C_1
	PINMUX_SET(I2C1_SCL, PB,10);
	PINMUX_SET(I2C1_SDA, PB,11);
#endif /* CONFIG_I2C_2 */
#ifdef CONFIG_SPI_0
#ifdef CONFIG_GD32_SPI_0_USE_HW_SS
	PINMUX_SET(SPI0_NSS,  PA,4);
#endif /* CONFIG_SPI_GD32_USE_HW_SS */
	PINMUX_SET(SPI0_SCK,  PA,5);
	PINMUX_SET(SPI0_MISO, PA,6);
	PINMUX_SET(SPI0_MOSI, PA,7);
#endif /* CONFIG_SPI_0 */
#ifdef CONFIG_SPI_1
#ifdef CONFIG_GD32_SPI_1_USE_HW_SS
	PINMUX_SET(SPI1_NSS,  PB,12);
#endif /* CONFIG_SPI_GD32_USE_HW_SS */
	PINMUX_SET(SPI1_SCK,  PB,13);
	PINMUX_SET(SPI1_MISO, PB,14);
	PINMUX_SET(SPI1_MOSI, PB,15);
#endif /* CONFIG_SPI_1 */
#ifdef CONFIG_SPI_2
#ifdef CONFIG_GD32_SPI_2_USE_HW_SS
	PINMUX_SET(SPI2_NSS,  PA,15);
#endif /* CONFIG_SPI_GD32_USE_HW_SS */
	PINMUX_SET(SPI2_SCK,  PB,3);
	PINMUX_SET(SPI2_MISO, PB,4);
	PINMUX_SET(SPI2_MOSI, PB,5);
#endif /* CONFIG_SPI_2 */
#ifdef CONFIG_CAN_0
	PINMUX_SET(CAN0_TX, PA,11);
	PINMUX_SET(CAN0_RX, PA,12);
#endif /* CONFIG_I2C_1 */
#ifdef CONFIG_CAN_1
	PINMUX_SET(CAN1_TX, PB,12);
	PINMUX_SET(CAN1_RX, PB,13);
#endif /* CONFIG_I2C_2 */

	return 0;
}

SYS_INIT(pinmux_gd32_init, PRE_KERNEL_1, CONFIG_PINMUX_GD32_DEVICE_INITIALIZATION_PRIORITY);
